# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = "fedora.34"
# BOX = "fedora/34-cloud-base"
# BOX_VERSION = "34.20210423.0"
BOX = "bento/fedora-34"
BOX_VERSION = "202107.08.0"

HOSTNAME = "fedora"
NETWORK_TYPE = "private_network"
NETWORK_IP = "192.168.44.44"
MEMORY = 4096
CPU = 2
HOST_CODE_DIR = "~/code"
GUEST_CODE_DIR = "/home/vagrant/code"
# GUEST_CODE_DIR = "/mnt/code"

Vagrant.configure("2") do |config|

  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION
  config.vm.define VM_NAME

  config.vm.hostname = HOSTNAME
  config.vm.network NETWORK_TYPE, ip: NETWORK_IP, hostname: true
  config.vm.synced_folder HOST_CODE_DIR, GUEST_CODE_DIR, type: "nfs"  # default => type: "rsync"

  config.vm.provider "virtualbox" do |v|
    v.memory = MEMORY
    v.cpus = CPU
  end

  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '64GB'
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    # config.vbguest.auto_update = false
    # don't run dnf update otherwise kernel updates will cause issues with guest additions upgrades
    config.vbguest.installer_hooks[:before_install] = [
      # "dnf update -y",
      "dnf install -y gcc make perl kernel-devel-$(uname -r) bzip2 dkms",
      # "dnf update -y kernel-*",
    ]
  end

  config.vm.provision "shell", path: "./bin/provision/install_base.sh", privileged: false
  config.vm.provision "shell", path: "./bin/provision/install_podman.sh", privileged: false
  config.vm.provision "shell", path: "./bin/provision/install_docker.sh", privileged: false
  config.vm.provision "shell", path: "./bin/provision/install_anaconda.sh", privileged: false

end
