# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = "ubuntu-20.04"

BOX = "bento/ubuntu-20.04"
BOX_VERSION = "202107.28.0"

HOSTNAME = "ubuntu"
NETWORK_TYPE = "private_network"
NETWORK_IP = "192.168.56.27"
MEMORY = 4096
CPU = 2
HOST_CODE_DIR = "~/code"
GUEST_CODE_DIR = "/home/vagrant/code"
HOST_KUBE_DIR = "~/.kube"
GUEST_KUBE_DIR = "/home/vagrant/.kube"

Vagrant.configure("2") do |config|

  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION
  config.vm.define VM_NAME

  config.vm.hostname = HOSTNAME
  config.vm.network NETWORK_TYPE, ip: NETWORK_IP, hostname: true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder HOST_CODE_DIR, GUEST_CODE_DIR, type: "nfs"
  config.vm.synced_folder HOST_KUBE_DIR, GUEST_KUBE_DIR, type: "nfs"

  config.vm.provider "virtualbox" do |v|
    v.memory = MEMORY
    v.cpus = CPU
    v.name = VM_NAME
  end

  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '80GB'
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    # config.vbguest.auto_update = false
    # don't run dnf update otherwise kernel updates will cause issues with guest additions upgrades
    config.vbguest.installer_hooks[:before_install] = [
      "apt update -y",
      "apt install -y build-essential dkms linux-headers-$(uname -r)",
    ]
  end

  config.vm.provision "shell", path: "./bin/provision/upgrade_system.sh", privileged: true
  config.vm.provision "shell", path: "./bin/provision/install_docker.sh", privileged: true
  config.vm.provision "shell", path: "./bin/provision/install_kubectl.sh", privileged: true
  config.vm.provision "shell", path: "./bin/provision/install_anaconda.sh", privileged: false

end
